import { test, expect } from "@playwright/test";

test("saved chat, preview, task review and responsive navigation", async ({ page }, testInfo) => {
  await page.goto("/tests/fixture.html");
  await expect(page.getByRole("textbox", { name: "Message Kimi" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Work", exact: true })).toBeVisible();
  await expect(page.getByText("I've drafted a weekly digest", { exact: false })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("conversation.png"), fullPage: true });
  await page.getByRole("button", { name: /Review “Friday/ }).click();
  await expect(page.getByRole("button", { name: "Approve", exact: true })).toBeVisible();
  await page.getByText("Full task details", { exact: true }).click();
  await expect(page.getByText(/Reads messages from the workshop/)).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("work.png"), fullPage: true });
  await page.getByRole("button", { name: /community-notes.md/ }).last().click();
  await expect(page.getByRole("heading", { name: "Community notes", exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "View original" })).toHaveAttribute("href", "/api/files/digest/content");
  await page.getByRole("button", { name: "Close work panel" }).click();
  const plan = page.getByRole("main").getByRole("region", { name: "Plan" });
  await expect(plan).toHaveCount(1);
  await plan.scrollIntoViewIfNeeded();
  await expect(plan.getByText("Gather community highlights")).toBeVisible();
  await expect(plan.getByRole("status")).toHaveText("2 of 2 done");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole("textbox", { name: "Message Kimi" }).fill("Please keep the tone informal.");
  await page.getByRole("button", { name: "Send message" }).click();
  await expect(page.getByText(/I've kept your direction/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Stop response" })).toHaveCount(0);
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Open conversations" }).click();
  await page.getByRole("button", { name: "Options for A weekly community digest" }).click();
  await page.getByRole("button", { name: "Rename", exact: true }).click();
  await page.getByRole("dialog").getByRole("textbox").fill("Friday digest");
  await page.getByRole("button", { name: "Save name", exact: true }).click();
  await expect(page.getByRole("button", { name: "Friday digest", exact: true })).toBeVisible();
});

test("branch a response, navigate its parent, and bring a result back", async ({ page }, testInfo) => {
  await page.goto("/tests/fixture.html");
  await page.getByRole("main").getByRole("button", { name: "Branch from here", exact: true }).last().click();
  const parentLink = page.getByRole("button", { name: "Parent: A weekly community digest", exact: true });
  await expect(parentLink).toBeVisible();
  await expect(page.getByText("Copied conversation history", { exact: true })).toBeVisible();
  await expect(page.getByText("New work in this branch", { exact: true })).toBeVisible();
  await expect(page.getByText("I've drafted a weekly digest", { exact: false })).toBeVisible();
  await expect(page.getByRole("button", { name: "Stop response" })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Approve", exact: true })).toHaveCount(0);
  await page.getByRole("textbox", { name: "Message Kimi" }).fill("Explore another format.");
  await page.getByRole("button", { name: "Send message" }).click();
  await page.getByRole("button", { name: "Bring to parent", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "Response brought to parent." })).toBeVisible();
  await expect(page.getByText("Brought back from", { exact: false })).toBeVisible();
  await expect(parentLink).toHaveCount(0);
  await page.getByRole("button", { name: "Branch · A weekly community digest", exact: true }).last().click();
  await expect(parentLink).toBeVisible();
  await expect(page.getByText("Explore another format.", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Brought to parent", exact: true })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("branch.png"), fullPage: true });
  await parentLink.click();
  await expect(page.locator("#message-4")).toHaveClass(/highlighted-message/);
  await expect(page.locator("#message-4")).toBeFocused();
  await expect(page.getByText("Brought back from", { exact: false })).toBeVisible();
});

test("copy responses and code, with manual fallback when clipboard is blocked", async ({ page, context }) => {
  await context.grantPermissions(["clipboard-read", "clipboard-write"]);
  await page.goto("/tests/fixture.html");
  await page.getByRole("button", { name: "Copy code", exact: true }).click();
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe("This week: community highlights\n");
  await page.getByRole("button", { name: "Copy response", exact: true }).click();
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain("```text\nThis week: community highlights\n```");
  await page.evaluate(() => Object.defineProperty(navigator, "clipboard", { configurable: true, value: { writeText: () => Promise.reject(new Error("Blocked by client")) } }));
  await page.getByRole("button", { name: "Copy code", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Copy text", exact: true });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole("textbox", { name: "Text to copy" })).toHaveValue("This week: community highlights\n");
  await dialog.getByRole("button", { name: "Done", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
